# Generated by Django 3.2.9 on 2021-12-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='company_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
