# Generated by Django 3.2.9 on 2021-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
        migrations.AddField(
            model_name='about',
            name='interests',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='intro',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
