# Generated by Django 3.2.9 on 2021-12-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('repo_link', models.URLField(max_length=500, null=True)),
                ('live_link', models.URLField(max_length=500, null=True)),
                ('description', models.CharField(max_length=800, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
