# Generated by Django 3.2.9 on 2021-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='website',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
